import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api-ref/crawlab-api",
    },
    {
      type: "category",
      label: "Nodes",
      link: {
        type: "doc",
        id: "api-ref/nodes",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-node-list",
          label: "Get Node List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-node",
          label: "Create Node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-node-list",
          label: "Delete Node List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-node-list",
          label: "Batch Update Node List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-node-metrics",
          label: "Get Node Metrics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-node-by-id",
          label: "Get Node by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-node-by-id",
          label: "Replace Node by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-node-by-id",
          label: "Delete Node by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-node-by-id",
          label: "Update Node by ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-node-current-metrics-by-id",
          label: "Get Node Current Metrics by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-node-time-range-metrics-by-id",
          label: "Get Node Time Range Metrics by ID",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Projects",
      link: {
        type: "doc",
        id: "api-ref/projects",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-project-list",
          label: "Get Project List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-project",
          label: "Create Project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-project-list",
          label: "Delete Project List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-project-list",
          label: "Batch Update Project List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-project-by-id",
          label: "Get Project by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-project-by-id",
          label: "Replace Project by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-project-by-id",
          label: "Delete Project by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-project-by-id",
          label: "Update Project by ID",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Spiders",
      link: {
        type: "doc",
        id: "api-ref/spiders",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-spider-list",
          label: "Get Spider List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-spider",
          label: "Create Spider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-spider-list",
          label: "Delete Spider List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-spider-list",
          label: "Batch Update Spider List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-spider-by-id",
          label: "Get Spider by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-spider-by-id",
          label: "Replace Spider by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-spider-by-id",
          label: "Delete Spider by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-spider-by-id",
          label: "Update Spider by ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/delete-spider-file",
          label: "Delete Spider File",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/copy-spider-file",
          label: "Copy Spider File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/export-spider-files",
          label: "Export Spider Files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-spider-file-content",
          label: "Get Spider File Content",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-spider-file-info",
          label: "Get Spider File Info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/list-spider-files",
          label: "List Spider Files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/rename-spider-file",
          label: "Rename Spider File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/save-spider-file",
          label: "Save Spider File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/save-spider-dir",
          label: "Save Spider Dir",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-spider-results",
          label: "Get Spider Results",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/run-spider",
          label: "Run Spider",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schedules",
      link: {
        type: "doc",
        id: "api-ref/schedules",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-schedule-list",
          label: "Get Schedule List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-schedule",
          label: "Create Schedule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-schedule-list",
          label: "Delete Schedule List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-schedule-list",
          label: "Batch Update Schedule List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-schedule-by-id",
          label: "Get Schedule by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-schedule-by-id",
          label: "Replace Schedule by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-schedule-by-id",
          label: "Delete Schedule by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-schedule-by-id",
          label: "Update Schedule by ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/disable-schedule",
          label: "Disable Schedule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/enable-schedule",
          label: "Enable Schedule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/run-schedule",
          label: "Run Schedule",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Tasks",
      link: {
        type: "doc",
        id: "api-ref/tasks",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-task-list",
          label: "Get Task List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-task",
          label: "Create Task",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-task-list",
          label: "Delete Task List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-task-list",
          label: "Batch Update Task List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/run-task",
          label: "Run Task",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-task-by-id",
          label: "Get Task by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-task-by-id",
          label: "Replace Task by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-task-by-id",
          label: "Delete Task by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-task-by-id",
          label: "Update Task by ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/cancel-task",
          label: "Cancel Task",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-task-logs",
          label: "Get Task Logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/restart-task",
          label: "Restart Task",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-task-results",
          label: "Get Task Results",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      link: {
        type: "doc",
        id: "api-ref/users",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-user-list",
          label: "Get User List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-user",
          label: "Create User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-user-list",
          label: "Delete User List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-user-list",
          label: "Batch Update User List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-me",
          label: "Get Me",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-me",
          label: "Replace Me",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/change-my-password",
          label: "Change My Password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-user-by-id",
          label: "Get User by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-user-by-id",
          label: "Replace User by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-user-by-id",
          label: "Delete User by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-user-by-id",
          label: "Update User by ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/change-user-password",
          label: "Change User Password",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Tokens",
      link: {
        type: "doc",
        id: "api-ref/tokens",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-token-list",
          label: "Get Token List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-token",
          label: "Create Token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-token-list",
          label: "Delete Token List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-token-list",
          label: "Batch Update Token List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-token-by-id",
          label: "Get Token by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-token-by-id",
          label: "Replace Token by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-token-by-id",
          label: "Delete Token by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-token-by-id",
          label: "Update Token by ID",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Environments",
      link: {
        type: "doc",
        id: "api-ref/environments",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-environment-list",
          label: "Get Environment List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-environment",
          label: "Create Environment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-environment-list",
          label: "Delete Environment List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-environment-list",
          label: "Batch Update Environment List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-environment-by-id",
          label: "Get Environment by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-environment-by-id",
          label: "Replace Environment by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-environment-by-id",
          label: "Delete Environment by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-environment-by-id",
          label: "Update Environment by ID",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Data Collections",
      link: {
        type: "doc",
        id: "api-ref/data-collections",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-data-collection-list",
          label: "Get Data Collection List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-data-collection",
          label: "Create Data Collection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-data-collection-list",
          label: "Delete Data Collection List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-data-collection-list",
          label: "Batch Update Data Collection List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-data-collection-by-id",
          label: "Get Data Collection by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-data-collection-by-id",
          label: "Replace Data Collection by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-data-collection-by-id",
          label: "Delete Data Collection by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-data-collection-by-id",
          label: "Update Data Collection by ID",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Export",
      link: {
        type: "doc",
        id: "api-ref/export",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/export-data",
          label: "Export Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-export",
          label: "Get Export",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-export-download",
          label: "Get Export Download",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Filters",
      link: {
        type: "doc",
        id: "api-ref/filters",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-filter-column-field-options",
          label: "Get Filter Column Field Options",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-filter-col-field-options-with-value",
          label: "Get Filter Col Field Options With Value",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-filter-col-field-options-with-value-and-label",
          label: "Get Filter Col Field Options With Value And Label",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings",
      link: {
        type: "doc",
        id: "api-ref/settings",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-setting",
          label: "Get Setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-setting-by-type",
          label: "Replace Setting by Type",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/create-setting",
          label: "Create Setting",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Stats",
      link: {
        type: "doc",
        id: "api-ref/stats",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-stats-daily",
          label: "Get Stats Daily",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-stats-overview",
          label: "Get Stats Overview",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-stats-tasks",
          label: "Get Stats Tasks",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "System",
      link: {
        type: "doc",
        id: "api-ref/system",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-system-info",
          label: "Get System Info",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Auth",
      link: {
        type: "doc",
        id: "api-ref/auth",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/login",
          label: "Login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/logout",
          label: "Logout",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Sync",
      link: {
        type: "doc",
        id: "api-ref/sync",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/download-file-sync",
          label: "Download file (sync)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/scan-files-sync",
          label: "Scan files (sync)",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Git",
      link: {
        type: "doc",
        id: "api-ref/git",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-git-list",
          label: "Get Git List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-git",
          label: "Create Git",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-git-list",
          label: "Delete Git List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-git-list",
          label: "Batch Update Git List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-git-by-id",
          label: "Get Git by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-git-by-id",
          label: "Replace Git by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-git-by-id",
          label: "Delete Git by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-git-by-id",
          label: "Update Git by ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-git-branches",
          label: "Get Git Branches",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/delete-git-branch",
          label: "Delete Git Branch",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/checkout-git-branch",
          label: "Checkout Git Branch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-git-current-branch",
          label: "Get Git Current Branch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-git-new-branch",
          label: "Create Git New Branch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-git-remote-branches",
          label: "Get Git Remote Branches",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/checkout-git-remote-branch",
          label: "Checkout Git Remote Branch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-git-changes",
          label: "Get Git Changes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/post-git-changes",
          label: "Post Git Changes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-git-changes",
          label: "Delete Git Changes",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/clone-git",
          label: "Clone Git",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/commit-git",
          label: "Commit Git",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-git-file",
          label: "Delete Git File",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/copy-git-file",
          label: "Copy Git File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-git-file-diff",
          label: "Get Git File Diff",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/export-git",
          label: "Export Git",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-git-file",
          label: "Get Git File",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-git-file-info",
          label: "Get Git File Info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-git-list-dir",
          label: "Get Git List Dir",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/rename-git-file",
          label: "Rename Git File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/save-git-file",
          label: "Save Git File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/save-git-dir",
          label: "Save Git Dir",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-git-logs",
          label: "Get Git Logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/pull-git",
          label: "Pull Git",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/push-git",
          label: "Push Git",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/create-git-spider",
          label: "Create Git Spider",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Dependencies",
      link: {
        type: "doc",
        id: "api-ref/dependencies",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-dependency-config",
          label: "Get Dependency Config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-dependency-config",
          label: "Replace Dependency Config",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/get-dependency-config-setup-list",
          label: "Get Dependency Config Setup List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/install-dependency-config-setup",
          label: "Install Dependency Config Setup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/uninstall-dependency-config-setup",
          label: "Uninstall Dependency Config Setup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-dependency-config-versions",
          label: "Get Dependency Config Versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-dependency-repo-list",
          label: "Get Dependency Repo List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/install-dependency",
          label: "Install Dependency",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-dependency-search-repo-list",
          label: "Get Dependency Search Repo List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/uninstall-dependency",
          label: "Uninstall Dependency",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-dependency-repo-version-list",
          label: "Get Dependency Repo Version List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-dependencies-setting-list",
          label: "Get Dependencies Setting List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-dependencies-setting",
          label: "Create Dependencies Setting",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-dependencies-setting-list",
          label: "Delete Dependencies Setting List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-dependencies-setting-list",
          label: "Batch Update Dependencies Setting List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-dependencies-setting-by-id",
          label: "Get Dependencies Setting by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-dependencies-setting-by-id",
          label: "Replace Dependencies Setting by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-dependencies-setting-by-id",
          label: "Delete Dependencies Setting by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-dependencies-setting-by-id",
          label: "Update Dependencies Setting by ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-dependency-spider-dependency-list",
          label: "Get Dependency Spider Dependency List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/install-dependency-spider",
          label: "Install Dependency Spider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-dependency-logs-by-id",
          label: "Get Dependency Logs by ID",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Notification Settings",
      link: {
        type: "doc",
        id: "api-ref/notification-settings",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-notification-setting-list",
          label: "Get Notification Setting List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-notifications-setting",
          label: "Create Notifications Setting",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-notifications-setting-list",
          label: "Delete Notifications Setting List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-notifications-setting-list",
          label: "Batch Update Notifications Setting List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-notification-setting-by-id",
          label: "Get Notification Setting by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-notifications-setting-by-id",
          label: "Replace Notifications Setting by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-notifications-setting-by-id",
          label: "Delete Notifications Setting by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-notifications-setting-by-id",
          label: "Update Notifications Setting by ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/disable-notification-setting",
          label: "Disable Notification Setting",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/enable-notification-setting",
          label: "Enable Notification Setting",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-notification-setting-requests",
          label: "Get Notification Setting Requests",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Notification Channels",
      link: {
        type: "doc",
        id: "api-ref/notification-channels",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-notifications-channel-list",
          label: "Get Notifications Channel List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-notifications-channel",
          label: "Create Notifications Channel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-notifications-channel-list",
          label: "Delete Notifications Channel List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-notifications-channel-list",
          label: "Batch Update Notifications Channel List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-notifications-channel-by-id",
          label: "Get Notifications Channel by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-notifications-channel-by-id",
          label: "Replace Notifications Channel by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-notifications-channel-by-id",
          label: "Delete Notifications Channel by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-notifications-channel-by-id",
          label: "Update Notifications Channel by ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/test-notification-channel",
          label: "Test Notification Channel",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Notification Requests",
      link: {
        type: "doc",
        id: "api-ref/notification-requests",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-notification-request-list",
          label: "Get Notification Request List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-notifications-request",
          label: "Create Notifications Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-notifications-request-list",
          label: "Delete Notifications Request List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-notifications-request-list",
          label: "Batch Update Notifications Request List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-notifications-request-by-id",
          label: "Get Notifications Request by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-notifications-request-by-id",
          label: "Replace Notifications Request by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-notifications-request-by-id",
          label: "Delete Notifications Request by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-notifications-request-by-id",
          label: "Update Notifications Request by ID",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Notification Alerts",
      link: {
        type: "doc",
        id: "api-ref/notification-alerts",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-notifications-alert-list",
          label: "Get Notifications Alert List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-notifications-alert",
          label: "Create Notifications Alert",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-notifications-alert-list",
          label: "Delete Notifications Alert List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-notifications-alert-list",
          label: "Batch Update Notifications Alert List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-notifications-alert-by-id",
          label: "Get Notifications Alert by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-notifications-alert-by-id",
          label: "Replace Notifications Alert by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-notifications-alert-by-id",
          label: "Delete Notifications Alert by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-notifications-alert-by-id",
          label: "Update Notifications Alert by ID",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Node Groups",
      link: {
        type: "doc",
        id: "api-ref/node-groups",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-node-group-list",
          label: "Get Node Group List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-node-group",
          label: "Create Node Group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-node-group-list",
          label: "Delete Node Group List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/get-node-group-by-id",
          label: "Get Node Group by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/update-node-group-by-id",
          label: "Update Node Group by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-node-group-by-id",
          label: "Delete Node Group by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/add-node-to-group",
          label: "Add Node to Group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/remove-node-from-group",
          label: "Remove Node from Group",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Databases",
      link: {
        type: "doc",
        id: "api-ref/databases",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-database-list",
          label: "Get Database List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-database",
          label: "Create Database",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-database-list",
          label: "Delete Database List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-database-list",
          label: "Batch Update Database List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-database-metrics",
          label: "Get Database Metrics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-database-by-id",
          label: "Get Database by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-database-by-id",
          label: "Replace Database by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-database-by-id",
          label: "Delete Database by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-database-by-id",
          label: "Update Database by ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-database-column-types",
          label: "Get Database Column Types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/test-database-connection",
          label: "Test Database Connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/export-database",
          label: "Export Database",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-database-export",
          label: "Get Database Export",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-database-export-download",
          label: "Get Database Export Download",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-database-metadata",
          label: "Get Database Metadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-database-current-metrics-by-id",
          label: "Get Database Current Metrics by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-database-time-range-metrics-by-id",
          label: "Get Database Time Range Metrics by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-database-orm-compatibility",
          label: "Get Database ORM Compatibility",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/initialize-database-orm",
          label: "Initialize Database ORM",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-database-orm-status",
          label: "Get Database ORM Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/update-database-orm-status",
          label: "Update Database ORM Status",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/query-database",
          label: "Query Database",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/create-database-table",
          label: "Create Database Table",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-database-table-data",
          label: "Get Database Table Data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-database-table-data",
          label: "Create Database Table Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/get-database-table-data-with-filter",
          label: "Get Database Table Data with Filter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/drop-database-table",
          label: "Drop Database Table",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/get-database-table-metadata",
          label: "Get Database Table Metadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/get-database-table-metadata-with-filter",
          label: "Get Database Table Metadata with Filter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/modify-database-table",
          label: "Modify Database Table",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/rename-database-table",
          label: "Rename Database Table",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Roles",
      link: {
        type: "doc",
        id: "api-ref/roles",
      },
      items: [
        {
          type: "doc",
          id: "api-ref/get-role-list",
          label: "Get Role List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/create-role",
          label: "Create Role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-ref/delete-role-list",
          label: "Delete Role List",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/batch-update-role-list",
          label: "Batch Update Role List",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-ref/get-role-by-id",
          label: "Get Role by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-ref/replace-role-by-id",
          label: "Replace Role by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-ref/delete-role-by-id",
          label: "Delete Role by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-ref/update-role-by-id",
          label: "Update Role by ID",
          className: "api-method patch",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
