import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import apiSidebar from './docs/api-ref/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Get Started',
        description: 'Learn how to install, set up, and take your first steps with Crawlab. This section covers everything from initial deployment to your first project.',
      },
      items: [
        { type: 'autogenerated', dirName: 'getting-started' },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Guides',
        description: 'Detailed walkthroughes and practical instructions for using Crawlab effectively. Explore advanced features, integrations, and best practices.',
      },
      items: [
        { type: 'autogenerated', dirName: 'guides' },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: {
        type: 'generated-index',
        title: 'Concepts',
        description: 'Understand the core concepts behind Crawlab. Learn about tasks, spiders, projects, and more.',
      },
      items: [
        { type: 'autogenerated', dirName: 'concepts' },
      ],
    },
    {
      type: 'category',
      label: 'Technical Details',
      link: {
        type: 'generated-index',
        title: 'Technical Details',
        description: 'Explore the technical architecture and implementation details of Crawlab. Understand how components interact and how the system works under the hood.',
      },
      items: [
        { type: 'autogenerated', dirName: 'tech' },
      ],
    },
    {
      type: 'doc',
      id: 'faq',
      label: 'FAQ',
    },
  ],
  examplesSidebar: [
    {
      type: 'category',
      label: 'Examples',
      link: {
        type: 'generated-index',
        title: 'Examples',
        description: 'Explore a variety of example projects to help you get started with Crawlab. Each example includes a detailed guide and a downloadable project file.',
      },
      items: [
        { type: 'autogenerated', dirName: 'examples' },
      ],
    },
  ],
  apiSidebar,
};

export default sidebars;
